import React, { createContext, useContext, useState, ReactNode } from 'react'

type Language = 'en' | 'hi' | 'ta' | 'te' | 'bn' | 'pa'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    appName: 'Farm Biosecurity Portal',
    dashboard: 'Dashboard',
    riskAssessment: 'Risk Assessment',
    training: 'Training',
    compliance: 'Compliance',
    alerts: 'Alerts',
    community: 'Community',
    profile: 'Profile',
    logout: 'Logout',
    login: 'Login',
    register: 'Register',
    email: 'Email',
    password: 'Password',
    name: 'Name',
    role: 'Role',
    farmer: 'Farmer',
    vet: 'Veterinarian',
    authority: 'Authority',
    farmType: 'Farm Type',
    pig: 'Pig Farm',
    poultry: 'Poultry Farm',
    both: 'Both',
    location: 'Location',
    language: 'Language',
    welcome: 'Welcome',
    overview: 'Overview',
    recentAssessments: 'Recent Assessments',
    upcomingTasks: 'Upcoming Tasks',
    activeAlerts: 'Active Alerts',
    riskLevel: 'Risk Level',
    low: 'Low Risk',
    medium: 'Medium Risk',
    high: 'High Risk',
    startAssessment: 'Start Assessment',
    viewDetails: 'View Details',
    submit: 'Submit',
    cancel: 'Cancel',
    save: 'Save',
    close: 'Close',
    loading: 'Loading...',
    noData: 'No data available',
    vaccination: 'Vaccination',
    inspection: 'Inspection',
    sanitation: 'Sanitation',
    addRecord: 'Add Record',
    date: 'Date',
    details: 'Details',
    trainingModules: 'Training Modules',
    startLearning: 'Start Learning',
    completed: 'Completed',
    inProgress: 'In Progress',
    notStarted: 'Not Started',
    createPost: 'Create Post',
    title: 'Title',
    content: 'Content',
    category: 'Category',
    general: 'General',
    diseaseControl: 'Disease Control',
    feedManagement: 'Feed Management',
    wasteManagement: 'Waste Management',
    severity: 'Severity',
    critical: 'Critical',
    description: 'Description',
    createAlert: 'Create Alert',
    analytics: 'Analytics',
    totalUsers: 'Total Users',
    totalAssessments: 'Total Assessments',
    farmStats: 'Farm Statistics',
    riskDistribution: 'Risk Distribution',
  },
  hi: {
    appName: 'कृषि जैव सुरक्षा पोर्टल',
    dashboard: 'डैशबोर्ड',
    riskAssessment: 'जोखिम मूल्यांकन',
    training: 'प्रशिक्षण',
    compliance: 'अनुपालन',
    alerts: 'सचेतन',
    community: 'समुदाय',
    profile: 'प्रोफ़ाइल',
    logout: 'लॉग आउट',
    login: 'लॉगिन',
    register: 'पंजीकरण',
    email: 'ईमेल',
    password: 'पासवर्ड',
    name: 'नाम',
    role: 'भूमिका',
    farmer: 'किसान',
    vet: 'पशु चिकित्सक',
    authority: 'प्राधिकरण',
    farmType: 'फार्म प्रकार',
    pig: 'सुअर फार्म',
    poultry: 'पोल्ट्री फार्म',
    both: 'दोनों',
    location: 'स्थान',
    language: 'भाषा',
    welcome: 'स्वागत है',
    overview: 'अवलोकन',
    recentAssessments: 'हाल की मूल्यांकन',
    upcomingTasks: 'आगामी कार्य',
    activeAlerts: 'सक्रिय सचेतन',
    riskLevel: 'जोखिम स्तर',
    low: 'कम जोखिम',
    medium: 'मध्यम जोखिम',
    high: 'उच्च जोखिम',
    startAssessment: 'मूल्यांकन शुरू करें',
    viewDetails: 'विवरण देखें',
    submit: 'जमा करें',
    cancel: 'रद्द करें',
    save: 'सहेजें',
    close: 'बंद करें',
    loading: 'लोड हो रहा है...',
    noData: 'कोई डेटा उपलब्ध नहीं',
    vaccination: 'टीकाकरण',
    inspection: 'निरीक्षण',
    sanitation: 'स्वच्छता',
    addRecord: 'रिकॉर्ड जोड़ें',
    date: 'तारीख',
    details: 'विवरण',
    trainingModules: 'प्रशिक्षण मॉड्यूल',
    startLearning: 'सीखना शुरू करें',
    completed: 'पूर्ण',
    inProgress: 'प्रगति में',
    notStarted: 'शुरू नहीं हुआ',
    createPost: 'पोस्ट बनाएं',
    title: 'शीर्षक',
    content: 'सामग्री',
    category: 'श्रेणी',
    general: 'सामान्य',
    diseaseControl: 'रोग नियंत्रण',
    feedManagement: 'फ़ीड प्रबंधन',
    wasteManagement: 'अपशिष्ट प्रबंधन',
    severity: 'गंभीरता',
    critical: 'गंभीर',
    description: 'विवरण',
    createAlert: 'सचेतन बनाएं',
    analytics: 'विश्लेषण',
    totalUsers: 'कुल उपयोगकर्ता',
    totalAssessments: 'कुल मूल्यांकन',
    farmStats: 'फार्म आंकड़े',
    riskDistribution: 'जोखिम वितरण',
  },
  ta: {
    appName: 'பண்ணை உயிர் பாதுகாப்பு போர்டல்',
    dashboard: 'டாஷ்போர்டு',
    riskAssessment: 'ஆபத்து மதிப்பீடு',
    training: 'பயிற்சி',
    compliance: 'இணக்கம்',
    alerts: 'எச்சரிக்கைகள்',
    community: 'சமூகம்',
    profile: 'சுயவிவரம்',
    logout: 'வெளியேறு',
    login: 'உள்நுழைக',
    register: 'பதிவு',
    email: 'மின்னஞ்சல்',
    password: 'கடவுச்சொல்',
    name: 'பெயர்',
    role: 'பங்கு',
    farmer: 'விவசாயி',
    vet: 'கால்நடை மருத்துவர்',
    authority: 'அதிகாரம்',
    farmType: 'பண்ணை வகை',
    pig: 'பன்றி பண்ணை',
    poultry: 'கோழி பண்ணை',
    both: 'இரண்டும்',
    location: 'இடம்',
    language: 'மொழி',
    welcome: 'வரவேற்பு',
    overview: 'கண்ணோட்டம்',
    recentAssessments: 'சமீபத்திய மதிப்பீடுகள்',
    upcomingTasks: 'வரவிருக்கும் பணிகள்',
    activeAlerts: 'செயலில் எச்சரிக்கைகள்',
    riskLevel: 'ஆபத்து நிலை',
    low: 'குறைந்த ஆபத்து',
    medium: 'நடுத்தர ஆபத்து',
    high: 'உயர் ஆபத்து',
    startAssessment: 'மதிப்பீட்டைத் தொடங்கவும்',
    viewDetails: 'விவரங்களைக் காண்க',
    submit: 'சமர்ப்பிக்கவும்',
    cancel: 'ரத்து செய்',
    save: 'சேமி',
    close: 'மூடு',
    loading: 'ஏற்றுகிறது...',
    noData: 'தரவு இல்லை',
    vaccination: 'தடுப்பூசி',
    inspection: 'ஆய்வு',
    sanitation: 'சுகாதாரம்',
    addRecord: 'பதிவு சேர்க்கவும்',
    date: 'தேதி',
    details: 'விவரங்கள்',
    trainingModules: 'பயிற்சி தொகுதிகள்',
    startLearning: 'கற்றல் தொடங்கவும்',
    completed: 'முடிந்தது',
    inProgress: 'நடந்து கொண்டிருக்கிறது',
    notStarted: 'தொடங்கவில்லை',
    createPost: 'பதிவை உருவாக்கவும்',
    title: 'தலைப்பு',
    content: 'உள்ளடக்கம்',
    category: 'வகை',
    general: 'பொது',
    diseaseControl: 'நோய் கட்டுப்பாடு',
    feedManagement: 'தீவன மேலாண்மை',
    wasteManagement: 'கழிவு மேலாண்மை',
    severity: 'தீவிரம்',
    critical: 'முக்கியமான',
    description: 'விளக்கம்',
    createAlert: 'எச்சரிக்கையை உருவாக்கவும்',
    analytics: 'பகுப்பாய்வு',
    totalUsers: 'மொத்த பயனர்கள்',
    totalAssessments: 'மொத்த மதிப்பீடுகள்',
    farmStats: 'பண்ணை புள்ளிவிவரங்கள்',
    riskDistribution: 'ஆபத்து விநியோகம்',
  },
  te: {
    appName: 'వ్యవసాయ జీవ భద్రత పోర్టల్',
    dashboard: 'డాష్బోర్డ్',
    riskAssessment: 'ప్రమాద అంచనా',
    training: 'శిక్షణ',
    compliance: 'అనుగుణత',
    alerts: 'హెచ్చరికలు',
    community: 'సమాజం',
    profile: 'ప్రొఫైల్',
    logout: 'లాగ్అవుట్',
    login: 'లాగిన్',
    register: 'నమోదు',
    email: 'ఇమెయిల్',
    password: 'పాస్వర్డ్',
    name: 'పేరు',
    role: 'పాత్ర',
    farmer: 'రైతు',
    vet: 'పశువైద్యుడు',
    authority: 'అధికారం',
    farmType: 'వ్యవసాయ రకం',
    pig: 'పంది వ్యవసాయం',
    poultry: 'పోల్ట్రీ వ్యవసాయం',
    both: 'రెండూ',
    location: 'స్థానం',
    language: 'భాష',
    welcome: 'స్వాగతం',
    overview: 'అవలోకనం',
    recentAssessments: 'ఇటీవలి అంచనాలు',
    upcomingTasks: 'రాబోయే పనులు',
    activeAlerts: 'క్రియాశీల హెచ్చరికలు',
    riskLevel: 'ప్రమాద స్థాయి',
    low: 'తక్కువ ప్రమాదం',
    medium: 'మధ్యస్థ ప్రమాదం',
    high: 'అధిక ప్రమాదం',
    startAssessment: 'అంచనా ప్రారంభించండి',
    viewDetails: 'వివరాలు చూడండి',
    submit: 'సమర్పించు',
    cancel: 'రద్దు చేయి',
    save: 'సేవ్ చేయి',
    close: 'మూసివేయి',
    loading: 'లోడ్ అవుతోంది...',
    noData: 'డేటా అందుబాటులో లేదు',
    vaccination: 'టీకా',
    inspection: 'తనిఖీ',
    sanitation: 'పరిశుభ్రత',
    addRecord: 'రికార్డ్ జోడించండి',
    date: 'తేదీ',
    details: 'వివరాలు',
    trainingModules: 'శిక్షణ మాడ్యూల్స్',
    startLearning: 'నేర్చుకోవడం ప్రారంభించండి',
    completed: 'పూర్తయింది',
    inProgress: 'పురోగతిలో ఉంది',
    notStarted: 'ప్రారంభించలేదు',
    createPost: 'పోస్ట్ సృష్టించండి',
    title: 'శీర్షిక',
    content: 'కంటెంట్',
    category: 'వర్గం',
    general: 'సాధారణ',
    diseaseControl: 'వ్యాధి నియంత్రణ',
    feedManagement: 'ఆహార నిర్వహణ',
    wasteManagement: 'వ్యర్థ నిర్వహణ',
    severity: 'తీవ్రత',
    critical: 'క్లిష్టమైన',
    description: 'వివరణ',
    createAlert: 'హెచ్చరికను సృష్టించండి',
    analytics: 'విశ్లేషణలు',
    totalUsers: 'మొత్తం వినియోగదారులు',
    totalAssessments: 'మొత్తం అంచనాలు',
    farmStats: 'వ్యవసాయ గణాంకాలు',
    riskDistribution: 'ప్రమాద పంపిణీ',
  },
  bn: {
    appName: 'খামার জৈব নিরাপত্তা পোর্টাল',
    dashboard: 'ড্যাশবোর্ড',
    riskAssessment: 'ঝুঁকি মূল্যায়ন',
    training: 'প্রশিক্ষণ',
    compliance: 'সম্মতি',
    alerts: 'সতর্কতা',
    community: 'সম্প্রদায়',
    profile: 'প্রোফাইল',
    logout: 'লগআউট',
    login: 'লগইন',
    register: 'নিবন্ধন',
    email: 'ইমেইল',
    password: 'পাসওয়ার্ড',
    name: 'নাম',
    role: 'ভূমিকা',
    farmer: 'কৃষক',
    vet: 'পশুচিকিৎসক',
    authority: 'কর্তৃপক্ষ',
    farmType: 'খামার প্রকার',
    pig: 'শুয়োরের খামার',
    poultry: 'পোল্ট্রি খামার',
    both: 'উভয়',
    location: 'অবস্থান',
    language: 'ভাষা',
    welcome: 'স্বাগতম',
    overview: 'সংক্ষিপ্ত বিবরণ',
    recentAssessments: 'সাম্প্রতিক মূল্যায়ন',
    upcomingTasks: 'আসন্ন কাজ',
    activeAlerts: 'সক্রিয় সতর্কতা',
    riskLevel: 'ঝুঁকির স্তর',
    low: 'কম ঝুঁকি',
    medium: 'মধ্যম ঝুঁকি',
    high: 'উচ্চ ঝুঁকি',
    startAssessment: 'মূল্যায়ন শুরু করুন',
    viewDetails: 'বিস্তারিত দেখুন',
    submit: 'জমা দিন',
    cancel: 'বাতিল',
    save: 'সংরক্ষণ',
    close: 'বন্ধ করুন',
    loading: 'লোড হচ্ছে...',
    noData: 'কোন তথ্য নেই',
    vaccination: 'টিকাকরণ',
    inspection: 'পরিদর্শন',
    sanitation: 'স্যানিটেশন',
    addRecord: 'রেকর্ড যোগ করুন',
    date: 'তারিখ',
    details: 'বিবরণ',
    trainingModules: 'প্রশিক্ষণ মডিউল',
    startLearning: 'শেখা শুরু করুন',
    completed: 'সম্পন্ন',
    inProgress: 'চলমান',
    notStarted: 'শুরু হয়নি',
    createPost: 'পোস্ট তৈরি করুন',
    title: 'শিরোনাম',
    content: 'বিষয়বস্তু',
    category: 'শ্রেণী',
    general: 'সাধারণ',
    diseaseControl: 'রোগ নিয়ন্ত্রণ',
    feedManagement: 'খাদ্য ব্যবস্থাপনা',
    wasteManagement: 'বর্জ্য ব্যবস্থাপনা',
    severity: 'তীব্রতা',
    critical: 'সমালোচনামূলক',
    description: 'বর্ণনা',
    createAlert: 'সতর্কতা তৈরি করুন',
    analytics: 'বিশ্লেষণ',
    totalUsers: 'মোট ব্যবহারকারী',
    totalAssessments: 'মোট মূল্যায়ন',
    farmStats: 'খামার পরিসংখ্যান',
    riskDistribution: 'ঝুঁকি বিতরণ',
  },
  pa: {
    appName: 'ਫਾਰਮ ਬਾਇਓਸਿਕਿਊਰਿਟੀ ਪੋਰਟਲ',
    dashboard: 'ਡੈਸ਼ਬੋਰਡ',
    riskAssessment: 'ਜੋਖਮ ਮੁਲਾਂਕਣ',
    training: 'ਸਿਖਲਾਈ',
    compliance: 'ਪਾਲਣਾ',
    alerts: 'ਚੇਤਾਵਨੀਆਂ',
    community: 'ਭਾਈਚਾਰਾ',
    profile: 'ਪ੍ਰੋਫਾਇਲ',
    logout: 'ਲਾਗਆਉਟ',
    login: 'ਲਾਗਇਨ',
    register: 'ਰਜਿਸਟਰ',
    email: 'ਈਮੇਲ',
    password: 'ਪਾਸਵਰਡ',
    name: 'ਨਾਮ',
    role: 'ਭੂਮਿਕਾ',
    farmer: 'ਕਿਸਾਨ',
    vet: 'ਪਸ਼ੂ ਚਿਕਿਤਸਕ',
    authority: 'ਅਥਾਰਟੀ',
    farmType: 'ਫਾਰਮ ਦੀ ਕਿਸਮ',
    pig: 'ਸੂਰ ਫਾਰਮ',
    poultry: 'ਪੋਲਟਰੀ ਫਾਰਮ',
    both: 'ਦੋਵੇਂ',
    location: 'ਸਥਾਨ',
    language: 'ਭਾਸ਼ਾ',
    welcome: 'ਸੁਆਗਤ ਹੈ',
    overview: 'ਸੰਖੇਪ ਜਾਣਕਾਰੀ',
    recentAssessments: 'ਤਾਜ਼ਾ ਮੁਲਾਂਕਣ',
    upcomingTasks: 'ਆਉਣ ਵਾਲੇ ਕੰਮ',
    activeAlerts: 'ਕਿਰਿਆਸ਼ੀਲ ਚੇਤਾਵਨੀਆਂ',
    riskLevel: 'ਜੋਖਮ ਪੱਧਰ',
    low: 'ਘੱਟ ਜੋਖਮ',
    medium: 'ਮੱਧਮ ਜੋਖਮ',
    high: 'ਉੱਚ ਜੋਖਮ',
    startAssessment: 'ਮੁਲਾਂਕਣ ਸ਼ੁਰੂ ਕਰੋ',
    viewDetails: 'ਵੇਰਵੇ ਵੇਖੋ',
    submit: 'ਜਮ੍ਹਾਂ ਕਰੋ',
    cancel: 'ਰੱਦ ਕਰੋ',
    save: 'ਸੇਵ ਕਰੋ',
    close: 'ਬੰਦ ਕਰੋ',
    loading: 'ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ...',
    noData: 'ਕੋਈ ਡਾਟਾ ਉਪਲਬਧ ਨਹੀਂ',
    vaccination: 'ਟੀਕਾਕਰਨ',
    inspection: 'ਨਿਰੀਖਣ',
    sanitation: 'ਸਫਾਈ',
    addRecord: 'ਰਿਕਾਰਡ ਸ਼ਾਮਲ ਕਰੋ',
    date: 'ਤਾਰੀਖ',
    details: 'ਵੇਰਵੇ',
    trainingModules: 'ਸਿਖਲਾਈ ਮੋਡਿਊਲ',
    startLearning: 'ਸਿੱਖਣਾ ਸ਼ੁਰੂ ਕਰੋ',
    completed: 'ਪੂਰਾ ਹੋਇਆ',
    inProgress: 'ਜਾਰੀ ਹੈ',
    notStarted: 'ਸ਼ੁਰੂ ਨਹੀਂ ਕੀਤਾ',
    createPost: 'ਪੋਸਟ ਬਣਾਓ',
    title: 'ਸਿਰਲੇਖ',
    content: 'ਸਮੱਗਰੀ',
    category: 'ਸ਼੍ਰੇਣੀ',
    general: 'ਆਮ',
    diseaseControl: 'ਬਿਮਾਰੀ ਨਿਯੰਤਰਣ',
    feedManagement: 'ਫੀਡ ਪ੍ਰਬੰਧਨ',
    wasteManagement: 'ਰਹਿੰਦ-ਖੂੰਹਦ ਪ੍ਰਬੰਧਨ',
    severity: 'ਗੰਭੀਰਤਾ',
    critical: 'ਨਾਜ਼ੁਕ',
    description: 'ਵਰਣਨ',
    createAlert: 'ਚੇਤਾਵਨੀ ਬਣਾਓ',
    analytics: 'ਵਿਸ਼ਲੇਸ਼ਣ',
    totalUsers: 'ਕੁੱਲ ਉਪਭੋਗਤਾ',
    totalAssessments: 'ਕੁੱਲ ਮੁਲਾਂਕਣ',
    farmStats: 'ਫਾਰਮ ਅੰਕੜੇ',
    riskDistribution: 'ਜੋਖਮ ਵੰਡ',
  },
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en')

  const t = (key: string): string => {
    return translations[language][key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}